### ISSUE TITLE
UDV's visor isn't fitting the screen

### ISSUE THREAD

**Issue by aBelcaldwell** [UndeadZeratul/hideous-helmet-extended#6]
![Screenshot_20230228-222401](https://user-images.githubusercontent.com/126602416/221926250-47421690-03d4-4fc5-b979-83ad0f06c4ec.png)
![Screenshot_20230228-222125](https://user-images.githubusercontent.com/126602416/221926259-aa07ffc8-73ae-4a52-9fcf-636f2995ef37.png)

The HUD doesn't correctly fit into both of the edges of the screen, and is even worse when I turn on full screen.

**Comment by UndeadZeratul** [comment]
As mentioned in the comment on the above commit, that should be enough to fix this.  Let me know if it does and I can close this.

EDIT: Almost forgot, the changes can be found on the `develop` branch, not `main`.

**Comment by aBelcaldwell** [comment]
it works now lol
